src/Entity/News.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NewsRepository")
 */
class News
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     */
    private $title;

    /**
     * @ORM\Column(type="string")
     */
    private $title_raw;

    /**
     * @ORM\Column(type="string")
     */
    private $author;

    /**
     * @ORM\Column(type="text")
     */
    private $text;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param mixed $title
     */
    public function setTitle($title): void
    {
        $this->title = $title;
    }

    /**
     * @return mixed
     */
    public function getTitleRaw()
    {
        return $this->title_raw;
    }

    /**
     * @param mixed $title_raw
     */
    public function setTitleRaw($title_raw): void
    {
        $this->title_raw = $title_raw;
    }

    /**
     * @return mixed
     */
    public function getAuthor()
    {
        return $this->author;
    }

    /**
     * @param mixed $author
     */
    public function setAuthor($author): void
    {
        $this->author = $author;
    }

    /**
     * @return mixed
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * @param mixed $text
     */
    public function setText($text): void
    {
        $this->text = $text;
    }

    /**
     * @return mixed
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * @param mixed $date
     */
    public function setData($date): void
    {
        $this->date = $date;
    }
}

templates/admin.html.twig
{% extends 'user.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/form.css') }}" type="text/css"/>
{% endblock %}

{% block content_header %}<h3>Panel Admina</h3>{% endblock %}
{% block content %}
    {% block userpanel %}{% endblock %}
    ADMINPAGE
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}GamersPlace - Twoje miejsce dla graczy{% endblock %}</title>
        {% block stylesheets %}
            <link rel="stylesheet" href="{{ asset('css/style.css') }}" type="text/css" />
        {% endblock %}
    </head>
    <body>
        {% block body %}
                    <div id="logo">
                    </div>
                    <div id="menubar">
                        <ul class="menu">
                            <li class=""><a href="{{ url('homepage') }}">Strona Główna</a></li>
                            <li class=""><a href="{{ url('newspage') }}">Newsy</a></li>
                        </ul>
                        <ul class="menu" id="menu_login">
                            {% if not is_granted('ROLE_USER') %}
                                <li><a href="{{ url('user_login') }}">Zaloguj</a></li>
                                <li><a href="{{ url('user_registration') }}">Zarejestruj</a></li>
                            {% else %}
                                {% if is_granted('ROLE_ADMIN') %}
                                    <li><a href="{{ url('adminpage') }}">Panel admina</a></li>
                                    {% endif %}
                                <li><a href="{{ url('userpage') }}">Panel użytkownika</a></li>
                                <li><a href="{{ url('logout') }}">Wyloguj</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
                <div id="site_content">
                    <div id="sidebar_container">
                        {% block userpanel %}
                        {% if is_granted('ROLE_USER')  %}
                        <div class="sidebar">
                            <div class="sidebar_top">
                                <h3>Panel Użytkownika</h3>
                            </div>
                            <div class="sidebar_item" id="panel">
                                Witaj {{ username }}!
                                <br /><br />
                                <a href="{{ url('user_change-password') }}">Zmień hasło</a><br />
                                <a href="{{ url('user_change-email') }}">Zmień e-mail</a>
                            </div>
                        </div>
                        {% endif %}
                        {% endblock %}
                        <div class="sidebar">
                            <div class="sidebar_top">
                                <h3>Tytuł</h3>
                            </div>
                            <div class="sidebar_item">
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt
                                ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
                                laboris nisi ut aliquip ex ea commodo consequat.
                            </div>
                        </div>
                        <div class="sidebar">
                            <div class="sidebar_top">
                                <h3>Tytuł</h3>
                            </div>
                            <div class="sidebar_item">
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt
                                ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
                                laboris nisi ut aliquip ex ea commodo consequat.
                            </div>
                        </div>
                    </div>
                    <div id="content_container">
                        <div id="content_header">{% block content_header %}<h3>Strona Główna</h3>{% endblock %}</div>
                        <div id="content">
                            {% block content %}
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt
                                ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
                                laboris nisi ut aliquip ex ea commodo consequat.Lorem ipsum dolor sit amet, consectetur adipisicing
                                    elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                                    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure
                                    dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
                                    occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                            {% endblock %}
                        </div>
                    </div>
                </div>
                <div id="footer">
                    <div id="footer_content">
                    <p><a href="{{ url('homepage') }}">Strona Główna</a> | <a href="{{ url('newspage') }}">Newsy</a></p>
                    <p>Copyright &copy; GamePlace 2018</p>
                    </div>
                </div>
        {% endblock %}
    </body>
</html>

templates/changeemail.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/form.css') }}" type="text/css"/>
{% endblock %}

{% block content_header %}<h3>Zmień e-mail</h3>{% endblock %}
{% block content %}
    {{ form_start(form) }}
    {% set email = old_email %}
    <div id="form">
        <div id="email">
                {{ form_label(form.email, 'Adres e-mail:') }}
                {{ form_widget(form.email, {'attr': {'value': (email)}}) }}
            </div>
            {{ form_errors(form.email) }}
        </div>
        <div id="submit">
            <button type="submit">Zmień e-mail</button>
        </div>
    </div>
    {{ form_end(form) }}

    {% for message in app.flashes('info') %}
        <div class="info">
            {{ message }}
        </div>
    {% endfor %}
{% endblock %}

templates/changepassword.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/form.css') }}" type="text/css"/>
{% endblock %}

{% block content_header %}<h3>Zmień hasło</h3>{% endblock %}
{% block content %}
    {{ form_start(form) }}
    <div id="form">
        <div id="password">
            <div id="first">
                {{ form_label(form.plainPassword.first) }}
                {{ form_widget(form.plainPassword.first) }}
            </div>
            <div id="second">
                {{ form_label(form.plainPassword.second) }}
                {{ form_widget(form.plainPassword.second) }}
            </div>
            {{ form_errors(form.plainPassword) }}
        </div>
        <div id="submit">
            <button type="submit">Zmień hasło</button>
        </div>
    </div>
    {{ form_end(form) }}

    {% for message in app.flashes('info') %}
        <div class="info">
            {{ message }}
        </div>
    {% endfor %}
{% endblock %}

templates/login.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/form.css') }}" type="text/css"/>
{% endblock %}

{% block content_header %}<h3>Logowanie</h3>{% endblock %}
{% block content %}
    {% block userpanel %}{% endblock %}
    {{ form_start(form, {'action': path('login_check')}) }}

    {% set username = last_username %}
    <div id="form">
        <div id="login">
            {{ form_label(form.login, 'Login: ') }}
            {{ form_widget(form.login, {'attr': {'name': 'login', 'value': (username)}}) }}
            {{ form_errors(form.login) }}
        </div>
        <div id="password">
            {{ form_label(form.password, 'Hasło: ') }}
            {{ form_widget(form.password, {'attr': {'name': 'password'}}) }}
            {{ form_errors(form.password) }}
        </div>
        <div id="remember_me">
            {{ form_widget(form.remember_me, {'attr': {'full_name': '_remember_me'}}) }}
            {{ form_label(form.remember_me, 'Zapamiętaj mnie') }}
            {{ form_errors(form.remember_me) }}
        </div>
        <div id="submit">
            <button type="submit">Zaloguj</button>
        </div>
    </div>
    {{ form_end(form) }}

    {% if error %}
        <div class="error">
            {{ error.messageKey|trans(error.messageData, 'security') }}
        </div>
    {% endif %}
{% endblock %}

templates/new.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/news.css') }}" type="text/css"/>
{% endblock %}

{% block content_header %}<h3>{{ new.title }}</h3>{% endblock %}
{% block content %}
            <div id="new">
                <div id="text">
                    {{ new.text }}
                    <br /><br />
                </div>
                <div id="author">
                    Autor: {{ new.author }}
                </div>
                <div id="date">
                    Data: {{ new.date|date('d/m/Y') }}
                </div>
                {% if is_granted('ROLE_ADMIN')  %}
                    <div id="button">
                        <a href="/news/delete/{{ new.titleRaw }}" class="button" id="delete">Usuń</a>
                    </div>
                {% endif %}
    </div>
{% endblock %}

templates/news.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/news.css') }}" type="text/css"/>
{% endblock %}

{% block content_header %}<h3>News</h3>{% endblock %}
{% block content %}
    <div id="news">
    {% for new in news|reverse %}
        <div id="new">
            <div id="title">
                <h4><a href="{{ url('newspage') }}/{{ new.titleRaw }}">{{ new.title }}</a></h4>
            </div>
            <div id="text">
                {% if new.text|length > 60 %}
                    {{ new.text|slice(0, 255) }}...
                {% else %}
                    {{ new.text }}
                {% endif %}
            </div>
            {% if is_granted('ROLE_ADMIN')  %}
                <div id="button">
                <a href="/news/delete/{{ new.titleRaw }}" class="button" id="delete">Usuń</a>
                </div>
            {% endif %}
        </div>
    {% endfor %}
    {% if is_granted('ROLE_ADMIN')  %}
        <a href="/news/add" class="button" id="add">Dodaj Newsa</a>
        {% endif %}
    </div>
{% endblock %}

templates/newsadd.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/form.css') }}" type="text/css"/>
{% endblock %}

{% block content_header %}<h3>Dodaj newsa</h3>{% endblock %}
{% block content %}
    {{ form_start(form) }}
    <div id="form">
        <div id="title">
            {{ form_label(form.title, 'Tytuł:') }}
            {{ form_widget(form.title) }}
            {{ form_errors(form.title) }}
        </div>
        <div id="text">
            {{ form_label(form.text, 'Treść:') }}
            {{ form_widget(form.text) }}
            {{ form_errors(form.text) }}
        </div>
        <div id="submit">
            <button type="submit">Dodaj</button>
        </div>
    </div>
    {{ form_end(form) }}
{% endblock %}

templates/registration.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/form.css') }}" type="text/css"/>
{% endblock %}

{% block content_header %}<h3>Rejestracja</h3>{% endblock %}
{% block content %}
    {% block userpanel %}{% endblock %}
    {{ form_start(form) }}
    <div id="form">
        <div id="login">
            {{ form_label(form.login, 'Login: ') }}
            {{ form_widget(form.login) }}
            {{ form_errors(form.login) }}
        </div>
        <div id="password">
            <div id="first">
                {{ form_label(form.plainPassword.first) }}
                {{ form_widget(form.plainPassword.first) }}
            </div>
            <div id="second">
                {{ form_label(form.plainPassword.second) }}
                {{ form_widget(form.plainPassword.second) }}
            </div>
            {{ form_errors(form.plainPassword) }}
        </div>
        <div id="email">
            {{ form_label(form.email, 'Adres e-mail: ') }}
            {{ form_widget(form.email) }}
            {{ form_errors(form.email) }}
        </div>
        <div id="submit">
            <button type="submit">Zarejestruj!</button>
        </div>
    </div>
    {{ form_end(form) }}

    {% for message in app.flashes('info') %}
        <div class="info">
            {{ message }}
        </div>
    {% endfor %}
{% endblock %}

templates/user.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/form.css') }}" type="text/css"/>
{% endblock %}

{% block content_header %}<h3>Panel użytkownika</h3>{% endblock %}
{% block content %}
    {% block userpanel %}{% endblock %}
    <ul id="user_panel">
        <li class=""><a href="{{ url('user_change-password') }}">Zmień hasło</a></li>
        <li class=""><a href="{{ url('user_change-email') }}">Zmień e-mail</a></li>
    </ul>
{% endblock %}